base_local_planner: base_local_planner/TrajectoryPlannerROS

TrajectoryPlannerROS:
    max_vel_x: 0.55
    min_vel_x: 0.05
    max_vel_theta: 1.4
    min_in_place_vel_theta: 0.2
  
    acc_lim_theta: 1.6
    acc_lim_x: 1.5
    acc_lim_y: 1.5
  
    holonomic_robot: true
