obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[0.1,0.1], [0.1,-0.1],[-0.1,-0.1],[-0.1,0.1]]
#robot_radius: 0.1
inflation_radius: 0.15

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_frame, data_type: LaserScan, topic: /mybot/laser_scan, marking: true, clearing: true}
